# Generated by Django 3.2.9 on 2021-11-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='estado',
        ),
        migrations.AddField(
            model_name='order',
            name='estado',
            field=models.CharField(blank=True, choices=[('En espera', 'En espera'), ('Aprobado', 'Aprobado'), ('No Aprobado', 'No Aprobado')], default='En espera', max_length=12),
        ),
    ]
